### ISSUE TITLE
複数立ち上げるとエラーが出る

### ISSUE THREAD

**Issue by mi-kei** [Khromium/PriParaSearch#4]
Kotlinのスレッドの問題？

```
Exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.IllegalStateException: bmp must not be null
	at work.airz.MediaIO.video2Hash(MediaIO.kt:75)
	at work.airz.MediaIO.videoProcessing(MediaIO.kt:33)
	at work.airz.Controller$launchThread$1.doResume(Controller.kt:87)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1409)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by mi-kei** [comment]
念のため動画の処理部分でnullチェックを挟んで対策かな

**Comment by mi-kei** [comment]
動画と音声フレームが違う問題に起因していた。
最後のフレームが動画フレームでない場合にnullが返ってくる仕様でした。

**Comment by mi-kei** [comment]
正常に動作することが確認できたのでcloseします
